import complex from './assets/complex.jpeg';
import exit from './assets/exit.jpeg';
import okeanos from './assets/okeanos.jpeg';
import shapeshifters from './assets/shapeshifters.jpeg';
import SouthSpecific from './assets/SouthSpecific.png';
import channelNoir from './assets/ChannelNoir.png';
import Inner from './assets/Inner.png';
import ultimateStation from './assets/ultimateStation.png';
import ShapeshifterSingle from './assets/ShapeshifterSingle.png';


export const PRODUCTS = [
{
    id: 0,
    productName: "We are Complex",
    productImage: complex,
    imageUrl: '/assets/complex.jpeg',
    productDescription: "CD, Digipack and digital streaming",
    label: "D-monic",
    yearReleased: "2010",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 10.00, 
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 1,
    productName: "Exit Real Life",
    productImage: exit,
    productDescription: "CD, Digipack and digital steaming",
    label: "D-monic",
    yearReleased: "2010",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 15.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 2,
    productName: "L'es Enfants des Okeanos",
    productImage: okeanos,
    productDescription: "record from CURL",
    label: "D-monic",
    yearReleased: "2010",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 15.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 3,
    productName: "Shapeshifters",
    productImage: shapeshifters,
    productDescription: "Heavyweight vinyl and CD Deluxe version and digital streaming",
    label: "Beth Shalom Records (Vinyl version",
    yearReleased: "2010",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 20.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 4,
    productName: "Channel Noir EP un",
    productImage: channelNoir,
    productDescription: "record from CURL",
    label: "D-monic",
    yearReleased: "2010",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 100.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 5,
    productName: "South Specific 2020",
    productImage: SouthSpecific,
    productDescription: "Compilation digital and CD release including 'Just like this' by CURL",
    label: "Brainboosters",
    yearReleased: "2010",
    linksLabel: "https://southspecific2020.bandcamp.com/track/24-curl-just-like-this",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 100.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 6,
    productName: "Inner",
    productImage: Inner,
    productDescription: "record from CURL",
    label: "EMI France",
    yearReleased: "2002",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 100.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 7,
    productName: "Ultimate Station",
    productImage: ultimateStation,
    productDescription: "record from CURL",
    label: "EMI France",
    yearReleased: "2002",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 100.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},
{
    id: 8,
    productName: "Shapeshifters Single",
    productImage: ShapeshifterSingle,
    productDescription: "record from CURL",
    label: "Beth Shalom Records",
    yearReleased: "2020",
    linksLabel: "https://d-monic.bandcamp.com/album/we-are-complex",
    linksShop: "https://www.manicdepression.fr/en/label/d-monic/",
    linksListen: "ha",
    price: 100.00,
    src:"https://open.spotify.com/embed/album/6NkzAyguw0zGhgnLcBbVvn?utm_source=generator&theme=0", 
    width:"100%",
    height:"500px", 
    allow:"autoplay", 
    loading:"lazy",    
    borderRadius:"12px",
},

]